# Generated by Django 3.1.5 on 2021-06-12 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='AddNewBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.IntegerField(unique=True, verbose_name='Accession ID')),
                ('date_of_entry', models.DateField(default=datetime.date.today, verbose_name='Date of Entry')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('alternate_title', models.CharField(max_length=200, verbose_name='Alternate Title')),
                ('publisher', models.CharField(max_length=200, verbose_name='Publisher')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='books.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language')),
            ],
            options={
                'verbose_name': 'New Book',
            },
        ),
    ]
