# Generated by Django 3.1.5 on 2021-06-16 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210616_2150'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='lang_name',
        ),
        migrations.AlterField(
            model_name='addnewbook',
            name='accession',
            field=models.PositiveIntegerField(unique=True, verbose_name='Accession ID'),
        ),
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for book across whole library', primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField(default=datetime.date(2021, 6, 16), verbose_name='Date Of Transaction')),
                ('due_back', models.DateField(default=datetime.date(2021, 6, 30), verbose_name='Due Back Date:')),
                ('is_renewed', models.BooleanField(default=False, verbose_name='Renewed')),
                ('status', models.CharField(blank=True, choices=[('Issue', 'Issue'), ('Reserve', 'Reserve'), ('Returned', 'Returned')], help_text='Book availability', max_length=10)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.addnewbook')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'verbose_name': 'Book Transaction',
                'ordering': ['due_back'],
                'unique_together': {('book', 'borrower')},
            },
        ),
    ]
