# Generated by Django 3.1.5 on 2021-06-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210616_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addnewbook',
            old_name='title',
            new_name='book_title',
        ),
    ]
