# Generated by Django 3.1.5 on 2021-06-24 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210616_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='Publisher')),
            ],
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.date(2021, 6, 25), verbose_name='Date Of Transaction'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='due_back',
            field=models.DateField(default=datetime.date(2021, 7, 9), verbose_name='Due Back Date:'),
        ),
        migrations.AlterField(
            model_name='addnewbook',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publisher'),
        ),
    ]
