# Generated by Django 3.1.5 on 2021-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Total cost of order', max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='orderNo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='booksuggestion',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Estimate price of the book', max_digits=10, verbose_name='Price'),
        ),
    ]
