# Generated by Django 3.1.5 on 2021-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmagazine',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Subscription Fee'),
        ),
    ]
