# Generated by Django 3.1.5 on 2021-06-14 12:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(help_text='Enter class and section', max_length=20, verbose_name='Class and Section')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='Enter academic session', max_length=20, verbose_name='Session')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('STD', 'Student'), ('EMP', 'Employee')], max_length=3, verbose_name='Member Type')),
                ('card', models.CharField(max_length=20, unique=True, verbose_name='Card Number')),
                ('si', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='SI Number')),
                ('admsn', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Admission Number')),
                ('employee', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_entry', models.DateField(default=datetime.date.today, verbose_name='Date of Entry')),
                ('father', models.CharField(blank=True, max_length=30, null=True, verbose_name="Father's Name")),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('\\+?\\d[\\d -]{8,12}\\d')], verbose_name='Phone No.')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, help_text='abc@xyz.com', max_length=254, null=True)),
                ('books_in_hand', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Books in Hand')),
                ('books_issued', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Books Issued')),
                ('textbooks_in_hand', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Textbooks in Hand')),
                ('magazines_in_hand', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Magazines in Hand')),
                ('late', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Late Returns')),
                ('remarks', models.CharField(default='NIL', max_length=200, null=True, verbose_name='Remarks')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.section')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.year')),
            ],
            options={
                'verbose_name': 'Member',
            },
        ),
    ]
