# Generated by Django 3.1.5 on 2021-06-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(help_text='Enter department', max_length=20, verbose_name='Department')),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['date_of_entry'], 'verbose_name': 'Member'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='admsn',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='member_name',
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.department'),
        ),
    ]
