# Generated by Django 3.1.5 on 2021-06-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210616_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='books_in_hand',
        ),
        migrations.RemoveField(
            model_name='member',
            name='books_issued',
        ),
        migrations.RemoveField(
            model_name='member',
            name='late',
        ),
        migrations.RemoveField(
            model_name='member',
            name='magazines_in_hand',
        ),
        migrations.RemoveField(
            model_name='member',
            name='textbooks_in_hand',
        ),
    ]
